/* soapH.h
   Generated by gSOAP 2.7.11 from temp.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_unsignedLONG64
#define SOAP_TYPE_unsignedLONG64 (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLONG64(struct soap*, ULONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLONG64(struct soap*, const ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLONG64(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_unsignedLONG64(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_unsignedLONG64(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfRainbowTableStatus
#define SOAP_TYPE_ns1__ArrayOfRainbowTableStatus (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfRainbowTableStatus(struct soap*, const char*, int, const ns1__ArrayOfRainbowTableStatus *, const char*);
SOAP_FMAC3 ns1__ArrayOfRainbowTableStatus * SOAP_FMAC4 soap_get_ns1__ArrayOfRainbowTableStatus(struct soap*, ns1__ArrayOfRainbowTableStatus *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfRainbowTableStatus * SOAP_FMAC4 soap_in_ns1__ArrayOfRainbowTableStatus(struct soap*, const char*, ns1__ArrayOfRainbowTableStatus *, const char*);
SOAP_FMAC5 ns1__ArrayOfRainbowTableStatus * SOAP_FMAC6 soap_new_ns1__ArrayOfRainbowTableStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfRainbowTableStatus(struct soap*, ns1__ArrayOfRainbowTableStatus*);
SOAP_FMAC3 ns1__ArrayOfRainbowTableStatus * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfRainbowTableStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfRainbowTableStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RainbowTableStatus
#define SOAP_TYPE_ns1__RainbowTableStatus (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RainbowTableStatus(struct soap*, const char*, int, const ns1__RainbowTableStatus *, const char*);
SOAP_FMAC3 ns1__RainbowTableStatus * SOAP_FMAC4 soap_get_ns1__RainbowTableStatus(struct soap*, ns1__RainbowTableStatus *, const char*, const char*);
SOAP_FMAC3 ns1__RainbowTableStatus * SOAP_FMAC4 soap_in_ns1__RainbowTableStatus(struct soap*, const char*, ns1__RainbowTableStatus *, const char*);
SOAP_FMAC5 ns1__RainbowTableStatus * SOAP_FMAC6 soap_new_ns1__RainbowTableStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RainbowTableStatus(struct soap*, ns1__RainbowTableStatus*);
SOAP_FMAC3 ns1__RainbowTableStatus * SOAP_FMAC4 soap_instantiate_ns1__RainbowTableStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RainbowTableStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfChainCheckHash
#define SOAP_TYPE_ns1__ArrayOfChainCheckHash (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfChainCheckHash(struct soap*, const char*, int, const ns1__ArrayOfChainCheckHash *, const char*);
SOAP_FMAC3 ns1__ArrayOfChainCheckHash * SOAP_FMAC4 soap_get_ns1__ArrayOfChainCheckHash(struct soap*, ns1__ArrayOfChainCheckHash *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfChainCheckHash * SOAP_FMAC4 soap_in_ns1__ArrayOfChainCheckHash(struct soap*, const char*, ns1__ArrayOfChainCheckHash *, const char*);
SOAP_FMAC5 ns1__ArrayOfChainCheckHash * SOAP_FMAC6 soap_new_ns1__ArrayOfChainCheckHash(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfChainCheckHash(struct soap*, ns1__ArrayOfChainCheckHash*);
SOAP_FMAC3 ns1__ArrayOfChainCheckHash * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfChainCheckHash(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfChainCheckHash(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ChainCheckHash
#define SOAP_TYPE_ns1__ChainCheckHash (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ChainCheckHash(struct soap*, const char*, int, const ns1__ChainCheckHash *, const char*);
SOAP_FMAC3 ns1__ChainCheckHash * SOAP_FMAC4 soap_get_ns1__ChainCheckHash(struct soap*, ns1__ChainCheckHash *, const char*, const char*);
SOAP_FMAC3 ns1__ChainCheckHash * SOAP_FMAC4 soap_in_ns1__ChainCheckHash(struct soap*, const char*, ns1__ChainCheckHash *, const char*);
SOAP_FMAC5 ns1__ChainCheckHash * SOAP_FMAC6 soap_new_ns1__ChainCheckHash(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ChainCheckHash(struct soap*, ns1__ChainCheckHash*);
SOAP_FMAC3 ns1__ChainCheckHash * SOAP_FMAC4 soap_instantiate_ns1__ChainCheckHash(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ChainCheckHash(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfIndexHash
#define SOAP_TYPE_ns1__ArrayOfIndexHash (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfIndexHash(struct soap*, const char*, int, const ns1__ArrayOfIndexHash *, const char*);
SOAP_FMAC3 ns1__ArrayOfIndexHash * SOAP_FMAC4 soap_get_ns1__ArrayOfIndexHash(struct soap*, ns1__ArrayOfIndexHash *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfIndexHash * SOAP_FMAC4 soap_in_ns1__ArrayOfIndexHash(struct soap*, const char*, ns1__ArrayOfIndexHash *, const char*);
SOAP_FMAC5 ns1__ArrayOfIndexHash * SOAP_FMAC6 soap_new_ns1__ArrayOfIndexHash(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfIndexHash(struct soap*, ns1__ArrayOfIndexHash*);
SOAP_FMAC3 ns1__ArrayOfIndexHash * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfIndexHash(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfIndexHash(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__IndexHash
#define SOAP_TYPE_ns1__IndexHash (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__IndexHash(struct soap*, const char*, int, const ns1__IndexHash *, const char*);
SOAP_FMAC3 ns1__IndexHash * SOAP_FMAC4 soap_get_ns1__IndexHash(struct soap*, ns1__IndexHash *, const char*, const char*);
SOAP_FMAC3 ns1__IndexHash * SOAP_FMAC4 soap_in_ns1__IndexHash(struct soap*, const char*, ns1__IndexHash *, const char*);
SOAP_FMAC5 ns1__IndexHash * SOAP_FMAC6 soap_new_ns1__IndexHash(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__IndexHash(struct soap*, ns1__IndexHash*);
SOAP_FMAC3 ns1__IndexHash * SOAP_FMAC4 soap_instantiate_ns1__IndexHash(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__IndexHash(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfWorkUnit
#define SOAP_TYPE_ns1__ArrayOfWorkUnit (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfWorkUnit(struct soap*, const char*, int, const ns1__ArrayOfWorkUnit *, const char*);
SOAP_FMAC3 ns1__ArrayOfWorkUnit * SOAP_FMAC4 soap_get_ns1__ArrayOfWorkUnit(struct soap*, ns1__ArrayOfWorkUnit *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfWorkUnit * SOAP_FMAC4 soap_in_ns1__ArrayOfWorkUnit(struct soap*, const char*, ns1__ArrayOfWorkUnit *, const char*);
SOAP_FMAC5 ns1__ArrayOfWorkUnit * SOAP_FMAC6 soap_new_ns1__ArrayOfWorkUnit(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfWorkUnit(struct soap*, ns1__ArrayOfWorkUnit*);
SOAP_FMAC3 ns1__ArrayOfWorkUnit * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfWorkUnit(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfWorkUnit(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__WorkUnit
#define SOAP_TYPE_ns1__WorkUnit (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__WorkUnit(struct soap*, const char*, int, const ns1__WorkUnit *, const char*);
SOAP_FMAC3 ns1__WorkUnit * SOAP_FMAC4 soap_get_ns1__WorkUnit(struct soap*, ns1__WorkUnit *, const char*, const char*);
SOAP_FMAC3 ns1__WorkUnit * SOAP_FMAC4 soap_in_ns1__WorkUnit(struct soap*, const char*, ns1__WorkUnit *, const char*);
SOAP_FMAC5 ns1__WorkUnit * SOAP_FMAC6 soap_new_ns1__WorkUnit(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__WorkUnit(struct soap*, ns1__WorkUnit*);
SOAP_FMAC3 ns1__WorkUnit * SOAP_FMAC4 soap_instantiate_ns1__WorkUnit(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__WorkUnit(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__MachineInfo
#define SOAP_TYPE_ns1__MachineInfo (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__MachineInfo(struct soap*, const char*, int, const ns1__MachineInfo *, const char*);
SOAP_FMAC3 ns1__MachineInfo * SOAP_FMAC4 soap_get_ns1__MachineInfo(struct soap*, ns1__MachineInfo *, const char*, const char*);
SOAP_FMAC3 ns1__MachineInfo * SOAP_FMAC4 soap_in_ns1__MachineInfo(struct soap*, const char*, ns1__MachineInfo *, const char*);
SOAP_FMAC5 ns1__MachineInfo * SOAP_FMAC6 soap_new_ns1__MachineInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__MachineInfo(struct soap*, ns1__MachineInfo*);
SOAP_FMAC3 ns1__MachineInfo * SOAP_FMAC4 soap_instantiate_ns1__MachineInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__MachineInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__rtgenDetails
#define SOAP_TYPE_ns1__rtgenDetails (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__rtgenDetails(struct soap*, const char*, int, const ns1__rtgenDetails *, const char*);
SOAP_FMAC3 ns1__rtgenDetails * SOAP_FMAC4 soap_get_ns1__rtgenDetails(struct soap*, ns1__rtgenDetails *, const char*, const char*);
SOAP_FMAC3 ns1__rtgenDetails * SOAP_FMAC4 soap_in_ns1__rtgenDetails(struct soap*, const char*, ns1__rtgenDetails *, const char*);
SOAP_FMAC5 ns1__rtgenDetails * SOAP_FMAC6 soap_new_ns1__rtgenDetails(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__rtgenDetails(struct soap*, ns1__rtgenDetails*);
SOAP_FMAC3 ns1__rtgenDetails * SOAP_FMAC4 soap_instantiate_ns1__rtgenDetails(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__rtgenDetails(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ArrayOfCPU
#define SOAP_TYPE_ns1__ArrayOfCPU (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfCPU(struct soap*, const char*, int, const ns1__ArrayOfCPU *, const char*);
SOAP_FMAC3 ns1__ArrayOfCPU * SOAP_FMAC4 soap_get_ns1__ArrayOfCPU(struct soap*, ns1__ArrayOfCPU *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfCPU * SOAP_FMAC4 soap_in_ns1__ArrayOfCPU(struct soap*, const char*, ns1__ArrayOfCPU *, const char*);
SOAP_FMAC5 ns1__ArrayOfCPU * SOAP_FMAC6 soap_new_ns1__ArrayOfCPU(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfCPU(struct soap*, ns1__ArrayOfCPU*);
SOAP_FMAC3 ns1__ArrayOfCPU * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfCPU(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfCPU(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__CPU
#define SOAP_TYPE_ns1__CPU (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__CPU(struct soap*, const char*, int, const ns1__CPU *, const char*);
SOAP_FMAC3 ns1__CPU * SOAP_FMAC4 soap_get_ns1__CPU(struct soap*, ns1__CPU *, const char*, const char*);
SOAP_FMAC3 ns1__CPU * SOAP_FMAC4 soap_in_ns1__CPU(struct soap*, const char*, ns1__CPU *, const char*);
SOAP_FMAC5 ns1__CPU * SOAP_FMAC6 soap_new_ns1__CPU(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__CPU(struct soap*, ns1__CPU*);
SOAP_FMAC3 ns1__CPU * SOAP_FMAC4 soap_instantiate_ns1__CPU(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__CPU(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__Credentials
#define SOAP_TYPE_ns1__Credentials (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Credentials(struct soap*, const char*, int, const ns1__Credentials *, const char*);
SOAP_FMAC3 ns1__Credentials * SOAP_FMAC4 soap_get_ns1__Credentials(struct soap*, ns1__Credentials *, const char*, const char*);
SOAP_FMAC3 ns1__Credentials * SOAP_FMAC4 soap_in_ns1__Credentials(struct soap*, const char*, ns1__Credentials *, const char*);
SOAP_FMAC5 ns1__Credentials * SOAP_FMAC6 soap_new_ns1__Credentials(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__Credentials(struct soap*, ns1__Credentials*);
SOAP_FMAC3 ns1__Credentials * SOAP_FMAC4 soap_instantiate_ns1__Credentials(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Credentials(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (8)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const xsd__base64Binary *, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, xsd__base64Binary *, const char*);
SOAP_FMAC5 xsd__base64Binary * SOAP_FMAC6 soap_new_xsd__base64Binary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__base64Binary(struct soap*, xsd__base64Binary*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_instantiate_xsd__base64Binary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__base64Binary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__RequestDetailedCrackingInfo
#define SOAP_TYPE_ns1__RequestDetailedCrackingInfo (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestDetailedCrackingInfo(struct soap*, struct ns1__RequestDetailedCrackingInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestDetailedCrackingInfo(struct soap*, const struct ns1__RequestDetailedCrackingInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestDetailedCrackingInfo(struct soap*, const struct ns1__RequestDetailedCrackingInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestDetailedCrackingInfo(struct soap*, const char*, int, const struct ns1__RequestDetailedCrackingInfo *, const char*);
SOAP_FMAC3 struct ns1__RequestDetailedCrackingInfo * SOAP_FMAC4 soap_get_ns1__RequestDetailedCrackingInfo(struct soap*, struct ns1__RequestDetailedCrackingInfo *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestDetailedCrackingInfo * SOAP_FMAC4 soap_in_ns1__RequestDetailedCrackingInfo(struct soap*, const char*, struct ns1__RequestDetailedCrackingInfo *, const char*);
SOAP_FMAC5 struct ns1__RequestDetailedCrackingInfo * SOAP_FMAC6 soap_new_ns1__RequestDetailedCrackingInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestDetailedCrackingInfo(struct soap*, struct ns1__RequestDetailedCrackingInfo*);
SOAP_FMAC3 struct ns1__RequestDetailedCrackingInfo * SOAP_FMAC4 soap_instantiate_ns1__RequestDetailedCrackingInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestDetailedCrackingInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RequestDetailedCrackingInfoResponse
#define SOAP_TYPE_ns1__RequestDetailedCrackingInfoResponse (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestDetailedCrackingInfoResponse(struct soap*, struct ns1__RequestDetailedCrackingInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestDetailedCrackingInfoResponse(struct soap*, const struct ns1__RequestDetailedCrackingInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestDetailedCrackingInfoResponse(struct soap*, const struct ns1__RequestDetailedCrackingInfoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestDetailedCrackingInfoResponse(struct soap*, const char*, int, const struct ns1__RequestDetailedCrackingInfoResponse *, const char*);
SOAP_FMAC3 struct ns1__RequestDetailedCrackingInfoResponse * SOAP_FMAC4 soap_get_ns1__RequestDetailedCrackingInfoResponse(struct soap*, struct ns1__RequestDetailedCrackingInfoResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestDetailedCrackingInfoResponse * SOAP_FMAC4 soap_in_ns1__RequestDetailedCrackingInfoResponse(struct soap*, const char*, struct ns1__RequestDetailedCrackingInfoResponse *, const char*);
SOAP_FMAC5 struct ns1__RequestDetailedCrackingInfoResponse * SOAP_FMAC6 soap_new_ns1__RequestDetailedCrackingInfoResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestDetailedCrackingInfoResponse(struct soap*, struct ns1__RequestDetailedCrackingInfoResponse*);
SOAP_FMAC3 struct ns1__RequestDetailedCrackingInfoResponse * SOAP_FMAC4 soap_instantiate_ns1__RequestDetailedCrackingInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestDetailedCrackingInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ReportError
#define SOAP_TYPE_ns1__ReportError (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ReportError(struct soap*, struct ns1__ReportError *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ReportError(struct soap*, const struct ns1__ReportError *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ReportError(struct soap*, const struct ns1__ReportError *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ReportError(struct soap*, const char*, int, const struct ns1__ReportError *, const char*);
SOAP_FMAC3 struct ns1__ReportError * SOAP_FMAC4 soap_get_ns1__ReportError(struct soap*, struct ns1__ReportError *, const char*, const char*);
SOAP_FMAC3 struct ns1__ReportError * SOAP_FMAC4 soap_in_ns1__ReportError(struct soap*, const char*, struct ns1__ReportError *, const char*);
SOAP_FMAC5 struct ns1__ReportError * SOAP_FMAC6 soap_new_ns1__ReportError(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ReportError(struct soap*, struct ns1__ReportError*);
SOAP_FMAC3 struct ns1__ReportError * SOAP_FMAC4 soap_instantiate_ns1__ReportError(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ReportError(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ReportErrorResponse
#define SOAP_TYPE_ns1__ReportErrorResponse (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ReportErrorResponse(struct soap*, struct ns1__ReportErrorResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ReportErrorResponse(struct soap*, const struct ns1__ReportErrorResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ReportErrorResponse(struct soap*, const struct ns1__ReportErrorResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ReportErrorResponse(struct soap*, const char*, int, const struct ns1__ReportErrorResponse *, const char*);
SOAP_FMAC3 struct ns1__ReportErrorResponse * SOAP_FMAC4 soap_get_ns1__ReportErrorResponse(struct soap*, struct ns1__ReportErrorResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__ReportErrorResponse * SOAP_FMAC4 soap_in_ns1__ReportErrorResponse(struct soap*, const char*, struct ns1__ReportErrorResponse *, const char*);
SOAP_FMAC5 struct ns1__ReportErrorResponse * SOAP_FMAC6 soap_new_ns1__ReportErrorResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ReportErrorResponse(struct soap*, struct ns1__ReportErrorResponse*);
SOAP_FMAC3 struct ns1__ReportErrorResponse * SOAP_FMAC4 soap_instantiate_ns1__ReportErrorResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ReportErrorResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__SendChainCheckResult
#define SOAP_TYPE_ns1__SendChainCheckResult (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__SendChainCheckResult(struct soap*, struct ns1__SendChainCheckResult *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__SendChainCheckResult(struct soap*, const struct ns1__SendChainCheckResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__SendChainCheckResult(struct soap*, const struct ns1__SendChainCheckResult *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SendChainCheckResult(struct soap*, const char*, int, const struct ns1__SendChainCheckResult *, const char*);
SOAP_FMAC3 struct ns1__SendChainCheckResult * SOAP_FMAC4 soap_get_ns1__SendChainCheckResult(struct soap*, struct ns1__SendChainCheckResult *, const char*, const char*);
SOAP_FMAC3 struct ns1__SendChainCheckResult * SOAP_FMAC4 soap_in_ns1__SendChainCheckResult(struct soap*, const char*, struct ns1__SendChainCheckResult *, const char*);
SOAP_FMAC5 struct ns1__SendChainCheckResult * SOAP_FMAC6 soap_new_ns1__SendChainCheckResult(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__SendChainCheckResult(struct soap*, struct ns1__SendChainCheckResult*);
SOAP_FMAC3 struct ns1__SendChainCheckResult * SOAP_FMAC4 soap_instantiate_ns1__SendChainCheckResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__SendChainCheckResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__SendChainCheckResultResponse
#define SOAP_TYPE_ns1__SendChainCheckResultResponse (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__SendChainCheckResultResponse(struct soap*, struct ns1__SendChainCheckResultResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__SendChainCheckResultResponse(struct soap*, const struct ns1__SendChainCheckResultResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__SendChainCheckResultResponse(struct soap*, const struct ns1__SendChainCheckResultResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SendChainCheckResultResponse(struct soap*, const char*, int, const struct ns1__SendChainCheckResultResponse *, const char*);
SOAP_FMAC3 struct ns1__SendChainCheckResultResponse * SOAP_FMAC4 soap_get_ns1__SendChainCheckResultResponse(struct soap*, struct ns1__SendChainCheckResultResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__SendChainCheckResultResponse * SOAP_FMAC4 soap_in_ns1__SendChainCheckResultResponse(struct soap*, const char*, struct ns1__SendChainCheckResultResponse *, const char*);
SOAP_FMAC5 struct ns1__SendChainCheckResultResponse * SOAP_FMAC6 soap_new_ns1__SendChainCheckResultResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__SendChainCheckResultResponse(struct soap*, struct ns1__SendChainCheckResultResponse*);
SOAP_FMAC3 struct ns1__SendChainCheckResultResponse * SOAP_FMAC4 soap_instantiate_ns1__SendChainCheckResultResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__SendChainCheckResultResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RequestChainCheck
#define SOAP_TYPE_ns1__RequestChainCheck (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestChainCheck(struct soap*, struct ns1__RequestChainCheck *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestChainCheck(struct soap*, const struct ns1__RequestChainCheck *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestChainCheck(struct soap*, const struct ns1__RequestChainCheck *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestChainCheck(struct soap*, const char*, int, const struct ns1__RequestChainCheck *, const char*);
SOAP_FMAC3 struct ns1__RequestChainCheck * SOAP_FMAC4 soap_get_ns1__RequestChainCheck(struct soap*, struct ns1__RequestChainCheck *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestChainCheck * SOAP_FMAC4 soap_in_ns1__RequestChainCheck(struct soap*, const char*, struct ns1__RequestChainCheck *, const char*);
SOAP_FMAC5 struct ns1__RequestChainCheck * SOAP_FMAC6 soap_new_ns1__RequestChainCheck(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestChainCheck(struct soap*, struct ns1__RequestChainCheck*);
SOAP_FMAC3 struct ns1__RequestChainCheck * SOAP_FMAC4 soap_instantiate_ns1__RequestChainCheck(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestChainCheck(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RequestChainCheckResponse
#define SOAP_TYPE_ns1__RequestChainCheckResponse (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestChainCheckResponse(struct soap*, struct ns1__RequestChainCheckResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestChainCheckResponse(struct soap*, const struct ns1__RequestChainCheckResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestChainCheckResponse(struct soap*, const struct ns1__RequestChainCheckResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestChainCheckResponse(struct soap*, const char*, int, const struct ns1__RequestChainCheckResponse *, const char*);
SOAP_FMAC3 struct ns1__RequestChainCheckResponse * SOAP_FMAC4 soap_get_ns1__RequestChainCheckResponse(struct soap*, struct ns1__RequestChainCheckResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestChainCheckResponse * SOAP_FMAC4 soap_in_ns1__RequestChainCheckResponse(struct soap*, const char*, struct ns1__RequestChainCheckResponse *, const char*);
SOAP_FMAC5 struct ns1__RequestChainCheckResponse * SOAP_FMAC6 soap_new_ns1__RequestChainCheckResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestChainCheckResponse(struct soap*, struct ns1__RequestChainCheckResponse*);
SOAP_FMAC3 struct ns1__RequestChainCheckResponse * SOAP_FMAC4 soap_instantiate_ns1__RequestChainCheckResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestChainCheckResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__UploadHashIndexList
#define SOAP_TYPE_ns1__UploadHashIndexList (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__UploadHashIndexList(struct soap*, struct ns1__UploadHashIndexList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__UploadHashIndexList(struct soap*, const struct ns1__UploadHashIndexList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__UploadHashIndexList(struct soap*, const struct ns1__UploadHashIndexList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__UploadHashIndexList(struct soap*, const char*, int, const struct ns1__UploadHashIndexList *, const char*);
SOAP_FMAC3 struct ns1__UploadHashIndexList * SOAP_FMAC4 soap_get_ns1__UploadHashIndexList(struct soap*, struct ns1__UploadHashIndexList *, const char*, const char*);
SOAP_FMAC3 struct ns1__UploadHashIndexList * SOAP_FMAC4 soap_in_ns1__UploadHashIndexList(struct soap*, const char*, struct ns1__UploadHashIndexList *, const char*);
SOAP_FMAC5 struct ns1__UploadHashIndexList * SOAP_FMAC6 soap_new_ns1__UploadHashIndexList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__UploadHashIndexList(struct soap*, struct ns1__UploadHashIndexList*);
SOAP_FMAC3 struct ns1__UploadHashIndexList * SOAP_FMAC4 soap_instantiate_ns1__UploadHashIndexList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__UploadHashIndexList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__UploadHashIndexListResponse
#define SOAP_TYPE_ns1__UploadHashIndexListResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__UploadHashIndexListResponse(struct soap*, struct ns1__UploadHashIndexListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__UploadHashIndexListResponse(struct soap*, const struct ns1__UploadHashIndexListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__UploadHashIndexListResponse(struct soap*, const struct ns1__UploadHashIndexListResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__UploadHashIndexListResponse(struct soap*, const char*, int, const struct ns1__UploadHashIndexListResponse *, const char*);
SOAP_FMAC3 struct ns1__UploadHashIndexListResponse * SOAP_FMAC4 soap_get_ns1__UploadHashIndexListResponse(struct soap*, struct ns1__UploadHashIndexListResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__UploadHashIndexListResponse * SOAP_FMAC4 soap_in_ns1__UploadHashIndexListResponse(struct soap*, const char*, struct ns1__UploadHashIndexListResponse *, const char*);
SOAP_FMAC5 struct ns1__UploadHashIndexListResponse * SOAP_FMAC6 soap_new_ns1__UploadHashIndexListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__UploadHashIndexListResponse(struct soap*, struct ns1__UploadHashIndexListResponse*);
SOAP_FMAC3 struct ns1__UploadHashIndexListResponse * SOAP_FMAC4 soap_instantiate_ns1__UploadHashIndexListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__UploadHashIndexListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RequestHashToIndex
#define SOAP_TYPE_ns1__RequestHashToIndex (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestHashToIndex(struct soap*, struct ns1__RequestHashToIndex *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestHashToIndex(struct soap*, const struct ns1__RequestHashToIndex *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestHashToIndex(struct soap*, const struct ns1__RequestHashToIndex *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestHashToIndex(struct soap*, const char*, int, const struct ns1__RequestHashToIndex *, const char*);
SOAP_FMAC3 struct ns1__RequestHashToIndex * SOAP_FMAC4 soap_get_ns1__RequestHashToIndex(struct soap*, struct ns1__RequestHashToIndex *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestHashToIndex * SOAP_FMAC4 soap_in_ns1__RequestHashToIndex(struct soap*, const char*, struct ns1__RequestHashToIndex *, const char*);
SOAP_FMAC5 struct ns1__RequestHashToIndex * SOAP_FMAC6 soap_new_ns1__RequestHashToIndex(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestHashToIndex(struct soap*, struct ns1__RequestHashToIndex*);
SOAP_FMAC3 struct ns1__RequestHashToIndex * SOAP_FMAC4 soap_instantiate_ns1__RequestHashToIndex(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestHashToIndex(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RequestHashToIndexResponse
#define SOAP_TYPE_ns1__RequestHashToIndexResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestHashToIndexResponse(struct soap*, struct ns1__RequestHashToIndexResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestHashToIndexResponse(struct soap*, const struct ns1__RequestHashToIndexResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestHashToIndexResponse(struct soap*, const struct ns1__RequestHashToIndexResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestHashToIndexResponse(struct soap*, const char*, int, const struct ns1__RequestHashToIndexResponse *, const char*);
SOAP_FMAC3 struct ns1__RequestHashToIndexResponse * SOAP_FMAC4 soap_get_ns1__RequestHashToIndexResponse(struct soap*, struct ns1__RequestHashToIndexResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestHashToIndexResponse * SOAP_FMAC4 soap_in_ns1__RequestHashToIndexResponse(struct soap*, const char*, struct ns1__RequestHashToIndexResponse *, const char*);
SOAP_FMAC5 struct ns1__RequestHashToIndexResponse * SOAP_FMAC6 soap_new_ns1__RequestHashToIndexResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestHashToIndexResponse(struct soap*, struct ns1__RequestHashToIndexResponse*);
SOAP_FMAC3 struct ns1__RequestHashToIndexResponse * SOAP_FMAC4 soap_instantiate_ns1__RequestHashToIndexResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestHashToIndexResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__UploadCompletedWork
#define SOAP_TYPE_ns1__UploadCompletedWork (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__UploadCompletedWork(struct soap*, struct ns1__UploadCompletedWork *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__UploadCompletedWork(struct soap*, const struct ns1__UploadCompletedWork *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__UploadCompletedWork(struct soap*, const struct ns1__UploadCompletedWork *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__UploadCompletedWork(struct soap*, const char*, int, const struct ns1__UploadCompletedWork *, const char*);
SOAP_FMAC3 struct ns1__UploadCompletedWork * SOAP_FMAC4 soap_get_ns1__UploadCompletedWork(struct soap*, struct ns1__UploadCompletedWork *, const char*, const char*);
SOAP_FMAC3 struct ns1__UploadCompletedWork * SOAP_FMAC4 soap_in_ns1__UploadCompletedWork(struct soap*, const char*, struct ns1__UploadCompletedWork *, const char*);
SOAP_FMAC5 struct ns1__UploadCompletedWork * SOAP_FMAC6 soap_new_ns1__UploadCompletedWork(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__UploadCompletedWork(struct soap*, struct ns1__UploadCompletedWork*);
SOAP_FMAC3 struct ns1__UploadCompletedWork * SOAP_FMAC4 soap_instantiate_ns1__UploadCompletedWork(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__UploadCompletedWork(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__UploadCompletedWorkResponse
#define SOAP_TYPE_ns1__UploadCompletedWorkResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__UploadCompletedWorkResponse(struct soap*, struct ns1__UploadCompletedWorkResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__UploadCompletedWorkResponse(struct soap*, const struct ns1__UploadCompletedWorkResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__UploadCompletedWorkResponse(struct soap*, const struct ns1__UploadCompletedWorkResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__UploadCompletedWorkResponse(struct soap*, const char*, int, const struct ns1__UploadCompletedWorkResponse *, const char*);
SOAP_FMAC3 struct ns1__UploadCompletedWorkResponse * SOAP_FMAC4 soap_get_ns1__UploadCompletedWorkResponse(struct soap*, struct ns1__UploadCompletedWorkResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__UploadCompletedWorkResponse * SOAP_FMAC4 soap_in_ns1__UploadCompletedWorkResponse(struct soap*, const char*, struct ns1__UploadCompletedWorkResponse *, const char*);
SOAP_FMAC5 struct ns1__UploadCompletedWorkResponse * SOAP_FMAC6 soap_new_ns1__UploadCompletedWorkResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__UploadCompletedWorkResponse(struct soap*, struct ns1__UploadCompletedWorkResponse*);
SOAP_FMAC3 struct ns1__UploadCompletedWorkResponse * SOAP_FMAC4 soap_instantiate_ns1__UploadCompletedWorkResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__UploadCompletedWorkResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RequestWork
#define SOAP_TYPE_ns1__RequestWork (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestWork(struct soap*, struct ns1__RequestWork *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestWork(struct soap*, const struct ns1__RequestWork *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestWork(struct soap*, const struct ns1__RequestWork *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestWork(struct soap*, const char*, int, const struct ns1__RequestWork *, const char*);
SOAP_FMAC3 struct ns1__RequestWork * SOAP_FMAC4 soap_get_ns1__RequestWork(struct soap*, struct ns1__RequestWork *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestWork * SOAP_FMAC4 soap_in_ns1__RequestWork(struct soap*, const char*, struct ns1__RequestWork *, const char*);
SOAP_FMAC5 struct ns1__RequestWork * SOAP_FMAC6 soap_new_ns1__RequestWork(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestWork(struct soap*, struct ns1__RequestWork*);
SOAP_FMAC3 struct ns1__RequestWork * SOAP_FMAC4 soap_instantiate_ns1__RequestWork(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestWork(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RequestWorkResponse
#define SOAP_TYPE_ns1__RequestWorkResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RequestWorkResponse(struct soap*, struct ns1__RequestWorkResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RequestWorkResponse(struct soap*, const struct ns1__RequestWorkResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RequestWorkResponse(struct soap*, const struct ns1__RequestWorkResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RequestWorkResponse(struct soap*, const char*, int, const struct ns1__RequestWorkResponse *, const char*);
SOAP_FMAC3 struct ns1__RequestWorkResponse * SOAP_FMAC4 soap_get_ns1__RequestWorkResponse(struct soap*, struct ns1__RequestWorkResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__RequestWorkResponse * SOAP_FMAC4 soap_in_ns1__RequestWorkResponse(struct soap*, const char*, struct ns1__RequestWorkResponse *, const char*);
SOAP_FMAC5 struct ns1__RequestWorkResponse * SOAP_FMAC6 soap_new_ns1__RequestWorkResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RequestWorkResponse(struct soap*, struct ns1__RequestWorkResponse*);
SOAP_FMAC3 struct ns1__RequestWorkResponse * SOAP_FMAC4 soap_instantiate_ns1__RequestWorkResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RequestWorkResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RegisterNewClient
#define SOAP_TYPE_ns1__RegisterNewClient (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RegisterNewClient(struct soap*, struct ns1__RegisterNewClient *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RegisterNewClient(struct soap*, const struct ns1__RegisterNewClient *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RegisterNewClient(struct soap*, const struct ns1__RegisterNewClient *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RegisterNewClient(struct soap*, const char*, int, const struct ns1__RegisterNewClient *, const char*);
SOAP_FMAC3 struct ns1__RegisterNewClient * SOAP_FMAC4 soap_get_ns1__RegisterNewClient(struct soap*, struct ns1__RegisterNewClient *, const char*, const char*);
SOAP_FMAC3 struct ns1__RegisterNewClient * SOAP_FMAC4 soap_in_ns1__RegisterNewClient(struct soap*, const char*, struct ns1__RegisterNewClient *, const char*);
SOAP_FMAC5 struct ns1__RegisterNewClient * SOAP_FMAC6 soap_new_ns1__RegisterNewClient(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RegisterNewClient(struct soap*, struct ns1__RegisterNewClient*);
SOAP_FMAC3 struct ns1__RegisterNewClient * SOAP_FMAC4 soap_instantiate_ns1__RegisterNewClient(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RegisterNewClient(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__RegisterNewClientResponse
#define SOAP_TYPE_ns1__RegisterNewClientResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RegisterNewClientResponse(struct soap*, struct ns1__RegisterNewClientResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RegisterNewClientResponse(struct soap*, const struct ns1__RegisterNewClientResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RegisterNewClientResponse(struct soap*, const struct ns1__RegisterNewClientResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RegisterNewClientResponse(struct soap*, const char*, int, const struct ns1__RegisterNewClientResponse *, const char*);
SOAP_FMAC3 struct ns1__RegisterNewClientResponse * SOAP_FMAC4 soap_get_ns1__RegisterNewClientResponse(struct soap*, struct ns1__RegisterNewClientResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__RegisterNewClientResponse * SOAP_FMAC4 soap_in_ns1__RegisterNewClientResponse(struct soap*, const char*, struct ns1__RegisterNewClientResponse *, const char*);
SOAP_FMAC5 struct ns1__RegisterNewClientResponse * SOAP_FMAC6 soap_new_ns1__RegisterNewClientResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__RegisterNewClientResponse(struct soap*, struct ns1__RegisterNewClientResponse*);
SOAP_FMAC3 struct ns1__RegisterNewClientResponse * SOAP_FMAC4 soap_instantiate_ns1__RegisterNewClientResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__RegisterNewClientResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__ArrayOfRainbowTableStatus
#define SOAP_TYPE_PointerTons1__ArrayOfRainbowTableStatus (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfRainbowTableStatus(struct soap*, ns1__ArrayOfRainbowTableStatus *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfRainbowTableStatus(struct soap*, ns1__ArrayOfRainbowTableStatus *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfRainbowTableStatus(struct soap*, const char *, int, ns1__ArrayOfRainbowTableStatus *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfRainbowTableStatus ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfRainbowTableStatus(struct soap*, ns1__ArrayOfRainbowTableStatus **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfRainbowTableStatus ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfRainbowTableStatus(struct soap*, const char*, ns1__ArrayOfRainbowTableStatus **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfChainCheckHash
#define SOAP_TYPE_PointerTons1__ArrayOfChainCheckHash (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfChainCheckHash(struct soap*, ns1__ArrayOfChainCheckHash *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfChainCheckHash(struct soap*, ns1__ArrayOfChainCheckHash *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfChainCheckHash(struct soap*, const char *, int, ns1__ArrayOfChainCheckHash *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfChainCheckHash ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfChainCheckHash(struct soap*, ns1__ArrayOfChainCheckHash **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfChainCheckHash ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfChainCheckHash(struct soap*, const char*, ns1__ArrayOfChainCheckHash **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfIndexHash
#define SOAP_TYPE_PointerTons1__ArrayOfIndexHash (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfIndexHash(struct soap*, ns1__ArrayOfIndexHash *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfIndexHash(struct soap*, ns1__ArrayOfIndexHash *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfIndexHash(struct soap*, const char *, int, ns1__ArrayOfIndexHash *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfIndexHash ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfIndexHash(struct soap*, ns1__ArrayOfIndexHash **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfIndexHash ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfIndexHash(struct soap*, const char*, ns1__ArrayOfIndexHash **, const char*);

#ifndef SOAP_TYPE_PointerTons1__rtgenDetails
#define SOAP_TYPE_PointerTons1__rtgenDetails (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__rtgenDetails(struct soap*, ns1__rtgenDetails *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__rtgenDetails(struct soap*, ns1__rtgenDetails *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__rtgenDetails(struct soap*, const char *, int, ns1__rtgenDetails *const*, const char *);
SOAP_FMAC3 ns1__rtgenDetails ** SOAP_FMAC4 soap_get_PointerTons1__rtgenDetails(struct soap*, ns1__rtgenDetails **, const char*, const char*);
SOAP_FMAC3 ns1__rtgenDetails ** SOAP_FMAC4 soap_in_PointerTons1__rtgenDetails(struct soap*, const char*, ns1__rtgenDetails **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfWorkUnit
#define SOAP_TYPE_PointerTons1__ArrayOfWorkUnit (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfWorkUnit(struct soap*, ns1__ArrayOfWorkUnit *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfWorkUnit(struct soap*, ns1__ArrayOfWorkUnit *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfWorkUnit(struct soap*, const char *, int, ns1__ArrayOfWorkUnit *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfWorkUnit ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfWorkUnit(struct soap*, ns1__ArrayOfWorkUnit **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfWorkUnit ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfWorkUnit(struct soap*, const char*, ns1__ArrayOfWorkUnit **, const char*);

#ifndef SOAP_TYPE_PointerTons1__MachineInfo
#define SOAP_TYPE_PointerTons1__MachineInfo (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__MachineInfo(struct soap*, ns1__MachineInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__MachineInfo(struct soap*, ns1__MachineInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__MachineInfo(struct soap*, const char *, int, ns1__MachineInfo *const*, const char *);
SOAP_FMAC3 ns1__MachineInfo ** SOAP_FMAC4 soap_get_PointerTons1__MachineInfo(struct soap*, ns1__MachineInfo **, const char*, const char*);
SOAP_FMAC3 ns1__MachineInfo ** SOAP_FMAC4 soap_in_PointerTons1__MachineInfo(struct soap*, const char*, ns1__MachineInfo **, const char*);

#ifndef SOAP_TYPE_PointerTons1__RainbowTableStatus
#define SOAP_TYPE_PointerTons1__RainbowTableStatus (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__RainbowTableStatus(struct soap*, ns1__RainbowTableStatus *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__RainbowTableStatus(struct soap*, ns1__RainbowTableStatus *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__RainbowTableStatus(struct soap*, const char *, int, ns1__RainbowTableStatus *const*, const char *);
SOAP_FMAC3 ns1__RainbowTableStatus ** SOAP_FMAC4 soap_get_PointerTons1__RainbowTableStatus(struct soap*, ns1__RainbowTableStatus **, const char*, const char*);
SOAP_FMAC3 ns1__RainbowTableStatus ** SOAP_FMAC4 soap_in_PointerTons1__RainbowTableStatus(struct soap*, const char*, ns1__RainbowTableStatus **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ChainCheckHash
#define SOAP_TYPE_PointerTons1__ChainCheckHash (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ChainCheckHash(struct soap*, ns1__ChainCheckHash *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ChainCheckHash(struct soap*, ns1__ChainCheckHash *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ChainCheckHash(struct soap*, const char *, int, ns1__ChainCheckHash *const*, const char *);
SOAP_FMAC3 ns1__ChainCheckHash ** SOAP_FMAC4 soap_get_PointerTons1__ChainCheckHash(struct soap*, ns1__ChainCheckHash **, const char*, const char*);
SOAP_FMAC3 ns1__ChainCheckHash ** SOAP_FMAC4 soap_in_PointerTons1__ChainCheckHash(struct soap*, const char*, ns1__ChainCheckHash **, const char*);

#ifndef SOAP_TYPE_PointerTons1__IndexHash
#define SOAP_TYPE_PointerTons1__IndexHash (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__IndexHash(struct soap*, ns1__IndexHash *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__IndexHash(struct soap*, ns1__IndexHash *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__IndexHash(struct soap*, const char *, int, ns1__IndexHash *const*, const char *);
SOAP_FMAC3 ns1__IndexHash ** SOAP_FMAC4 soap_get_PointerTons1__IndexHash(struct soap*, ns1__IndexHash **, const char*, const char*);
SOAP_FMAC3 ns1__IndexHash ** SOAP_FMAC4 soap_in_PointerTons1__IndexHash(struct soap*, const char*, ns1__IndexHash **, const char*);

#ifndef SOAP_TYPE_PointerTons1__WorkUnit
#define SOAP_TYPE_PointerTons1__WorkUnit (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__WorkUnit(struct soap*, ns1__WorkUnit *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__WorkUnit(struct soap*, ns1__WorkUnit *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__WorkUnit(struct soap*, const char *, int, ns1__WorkUnit *const*, const char *);
SOAP_FMAC3 ns1__WorkUnit ** SOAP_FMAC4 soap_get_PointerTons1__WorkUnit(struct soap*, ns1__WorkUnit **, const char*, const char*);
SOAP_FMAC3 ns1__WorkUnit ** SOAP_FMAC4 soap_in_PointerTons1__WorkUnit(struct soap*, const char*, ns1__WorkUnit **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfCPU
#define SOAP_TYPE_PointerTons1__ArrayOfCPU (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfCPU(struct soap*, ns1__ArrayOfCPU *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfCPU(struct soap*, ns1__ArrayOfCPU *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfCPU(struct soap*, const char *, int, ns1__ArrayOfCPU *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfCPU ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfCPU(struct soap*, ns1__ArrayOfCPU **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfCPU ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfCPU(struct soap*, const char*, ns1__ArrayOfCPU **, const char*);

#ifndef SOAP_TYPE_PointerTons1__Credentials
#define SOAP_TYPE_PointerTons1__Credentials (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Credentials(struct soap*, ns1__Credentials *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Credentials(struct soap*, ns1__Credentials *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Credentials(struct soap*, const char *, int, ns1__Credentials *const*, const char *);
SOAP_FMAC3 ns1__Credentials ** SOAP_FMAC4 soap_get_PointerTons1__Credentials(struct soap*, ns1__Credentials **, const char*, const char*);
SOAP_FMAC3 ns1__Credentials ** SOAP_FMAC4 soap_in_PointerTons1__Credentials(struct soap*, const char*, ns1__Credentials **, const char*);

#ifndef SOAP_TYPE_PointerTons1__CPU
#define SOAP_TYPE_PointerTons1__CPU (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__CPU(struct soap*, ns1__CPU *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__CPU(struct soap*, ns1__CPU *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__CPU(struct soap*, const char *, int, ns1__CPU *const*, const char *);
SOAP_FMAC3 ns1__CPU ** SOAP_FMAC4 soap_get_PointerTons1__CPU(struct soap*, ns1__CPU **, const char*, const char*);
SOAP_FMAC3 ns1__CPU ** SOAP_FMAC4 soap_in_PointerTons1__CPU(struct soap*, const char*, ns1__CPU **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__RainbowTableStatus
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__RainbowTableStatus (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, std::vector<ns1__RainbowTableStatus * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, const std::vector<ns1__RainbowTableStatus * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, const char*, int, const std::vector<ns1__RainbowTableStatus * >*, const char*);
SOAP_FMAC3 std::vector<ns1__RainbowTableStatus * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, const char*, std::vector<ns1__RainbowTableStatus * >*, const char*);
SOAP_FMAC5 std::vector<ns1__RainbowTableStatus * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, std::vector<ns1__RainbowTableStatus * >*);
SOAP_FMAC3 std::vector<ns1__RainbowTableStatus * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__RainbowTableStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__ChainCheckHash
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__ChainCheckHash (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, std::vector<ns1__ChainCheckHash * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, const std::vector<ns1__ChainCheckHash * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, const char*, int, const std::vector<ns1__ChainCheckHash * >*, const char*);
SOAP_FMAC3 std::vector<ns1__ChainCheckHash * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, const char*, std::vector<ns1__ChainCheckHash * >*, const char*);
SOAP_FMAC5 std::vector<ns1__ChainCheckHash * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, std::vector<ns1__ChainCheckHash * >*);
SOAP_FMAC3 std::vector<ns1__ChainCheckHash * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__ChainCheckHash(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__IndexHash
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__IndexHash (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, std::vector<ns1__IndexHash * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, const std::vector<ns1__IndexHash * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, const char*, int, const std::vector<ns1__IndexHash * >*, const char*);
SOAP_FMAC3 std::vector<ns1__IndexHash * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, const char*, std::vector<ns1__IndexHash * >*, const char*);
SOAP_FMAC5 std::vector<ns1__IndexHash * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, std::vector<ns1__IndexHash * >*);
SOAP_FMAC3 std::vector<ns1__IndexHash * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__IndexHash(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__WorkUnit
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__WorkUnit (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, std::vector<ns1__WorkUnit * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, const std::vector<ns1__WorkUnit * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, const char*, int, const std::vector<ns1__WorkUnit * >*, const char*);
SOAP_FMAC3 std::vector<ns1__WorkUnit * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, const char*, std::vector<ns1__WorkUnit * >*, const char*);
SOAP_FMAC5 std::vector<ns1__WorkUnit * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, std::vector<ns1__WorkUnit * >*);
SOAP_FMAC3 std::vector<ns1__WorkUnit * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__WorkUnit(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__CPU
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__CPU (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__CPU(struct soap*, std::vector<ns1__CPU * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__CPU(struct soap*, const std::vector<ns1__CPU * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__CPU(struct soap*, const char*, int, const std::vector<ns1__CPU * >*, const char*);
SOAP_FMAC3 std::vector<ns1__CPU * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__CPU(struct soap*, const char*, std::vector<ns1__CPU * >*, const char*);
SOAP_FMAC5 std::vector<ns1__CPU * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons1__CPU(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons1__CPU(struct soap*, std::vector<ns1__CPU * >*);
SOAP_FMAC3 std::vector<ns1__CPU * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__CPU(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__CPU(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
